spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/explore?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PWD}
    hikari:
      autoCommit: true
      connectionTimeOut: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 10
      minimumIdle: 1

logging:
  level:
    root: ERROR
  file:
    path: /home/zhangchi/workarea/code/explore/explore-be/log
    max-size: 10MB
    max-history: 10
    
mybatis:
  mapper-locations: classpath:com/zc/explore/dao/mapper/*.xml

app:
  protocol: http
  host: localhost:8080
  email:
    server: smtp.163.com
    from: welcome2expore@163.com
    pwd: ${SMTP_PWD}
    content_type: text/html
    subject: Explore
    activate_page_path: /user/activate
  jwt:
    alg: EC
    private_key_path: /home/zhangchi/opt/explore/key/ec
    public_key_path: /home/zhangchi/opt/explore/key/ec.pub
    expiration: 604800000
    key: email
